### ISSUE TITLE
What is your algorithm? 

### ISSUE THREAD

**Issue by hoseinm444** [Alby0n/Masked-Face-Recognition#9]
Hi Mr, I really want to know your algorithm to make this system because I want to make similar things for university article.
Can you tell me how should I start, which book is help full? And your algorithm and possible algorithms and things like that?

**Comment by Alby0n** [comment]
Face Detection is carried out by the caffe model using OpenCV and recognition is build on the principle of Siamese neural networks 

https://www.analyticsvidhya.com/blog/2022/04/face-detection-using-the-caffe-model/ (Caffe model)
